name: Generate Links and Deploy to GitHub Pages

on: 
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para actions/checkout
      pages: write    # Necesario para actions/deploy-pages
      id-token: write # Necesario para actions/deploy-pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run link generator script
      run: python generate_index_links.py

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Sube todo el directorio raíz como artefacto

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4